"""add field 'name' to event model

Revision ID: db1a6a889f8b
Revises: 41951b5767db
Create Date: 2025-02-24 15:52:10.980588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db1a6a889f8b'
down_revision: Union[str, None] = '41951b5767db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'name')
    # ### end Alembic commands ###
