version: '3.9'

services:
  line_provider_database:
    image: postgres:alpine
    env_file: line_provider/.env
    ports:
      - "5432:5432"
    volumes:
      - line_provider_postgres_data:/var/lib/postgresql/data

  bet_maker_database:
    image: postgres:alpine
    env_file: bet_maker/.env
    ports:
      - "5433:5432"
    volumes:
      - bet_makers_postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    env_file: line_provider/.env
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  redis:
    image: redis:7
    env_file: bet_maker/.env
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  line_provider:
    build:
      context: line_provider
      dockerfile: Dockerfile
    env_file: line_provider/.env
    command: [ "python", "src/main.py" ]
    ports:
      - "8080:8080"
    depends_on:
      - line_provider_database
      - rabbitmq

  bet_maker:
    build:
      context: bet_maker
      dockerfile: Dockerfile
    env_file: bet_maker/.env
    command: [ "python", "src/main.py" ]
    ports:
      - "8090:8090"
    depends_on:
      - bet_maker_database
      - rabbitmq

volumes:
  line_provider_postgres_data:
  bet_makers_postgres_data:
  redis_data:
  rabbitmq_data: