"""initial migration

Revision ID: 52d3e64318b0
Revises:
Create Date: 2024-11-02 22:45:38.282628

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "52d3e64318b0"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum("WIN", "LOSE", "PENDING", name="betstate").create(op.get_bind())
    op.create_table(
        "bets",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "state",
            postgresql.ENUM(
                "WIN", "LOSE", "PENDING", name="betstate", create_type=False
            ),
            nullable=False,
        ),
        sa.Column("sum", sa.Numeric(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bets")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("bets")
    sa.Enum("WIN", "LOSE", "PENDING", name="betstate").drop(op.get_bind())
    # ### end Alembic commands ###
