"""add event_id

Revision ID: 8832e2d659a9
Revises: 52d3e64318b0
Create Date: 2024-11-04 01:13:00.359197

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8832e2d659a9"
down_revision: Union[str, None] = "52d3e64318b0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("bets", sa.Column("event_id", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("bets", "event_id")
    # ### end Alembic commands ###
